### ISSUE TITLE
An error during launching

### ISSUE THREAD

**Issue by credo7** [Fryingpannn/ClientServer_PythonSocket#1]
Traceback (most recent call last):
  File "/Users/vitya/Desktop/pythonApp/server/server.py", line 55, in <module>
    main()
  File "/Users/vitya/Desktop/pythonApp/server/server.py", line 41, in main
    http = HTTPServerLibrary()
  File "/Users/vitya/Desktop/pythonApp/server/HTTPServerLibrary.py", line 17, in __init__
    self.fileHandler = FileHandler(verbose=False)
  File "/Users/vitya/Desktop/pythonApp/server/FileHandler.py", line 18, in __init__
    self.read_database()
  File "/Users/vitya/Desktop/pythonApp/server/FileHandler.py", line 23, in read_database
    raise Exception('Cannot read from database. Incorrect path or "data.txt" does not exist.')
Exception: Cannot read from database. Incorrect path or "data.txt" does not exist.

**Comment by Fryingpannn** [comment]
Rename the file "data-name-replaced.txt" to "data.txt" (in /server folder).

Btw are you on Mac or Windows?

**Comment by credo7** [comment]
> Rename the file "data-name-replaced.txt" to "data.txt" (in /server folder).
> 
> Btw are you on Mac or Windows?

Great! Now it works fine

Mac user
